defmodule Tincture.PublicApiTest do
  use ExUnit.Case, async: true

  # Snapshot of the API published in v0.3.2, the last released tag, checked against
  # the tree at fe0eebd. Anchored to the release rather than to main:
  # what Hex shipped is what users can be calling.
  #
  # The assertion is one-directional — snapshot is a subset of what exists now.
  # Adding a function, or a new arity, passes. Removing one, renaming it, or changing
  # its arity fails. Under semver those are breaking changes for a published package,
  # and this suite exists so they are a recorded decision rather than a side effect of
  # satisfying a linter: `lib/tincture.ex` is exempt from Credo's FunctionArity check
  # for exactly the same reason.
  #
  # To remove one deliberately, delete its entry in the same commit and say why.

  # Documented API: exported, and shown in the generated docs.
  @public_api [
    {Tincture, :add_bookmark, 3},
    {Tincture, :add_page, 1},
    {Tincture, :artifact, 2},
    {Tincture, :bezier, 7},
    {Tincture, :checkbox, 5},
    {Tincture, :checkbox, 6},
    {Tincture, :choice_field, 6},
    {Tincture, :choice_field, 7},
    {Tincture, :circle, 4},
    {Tincture, :circle, 5},
    {Tincture, :clip, 1},
    {Tincture, :clip_even_odd, 1},
    {Tincture, :encrypt, 1},
    {Tincture, :encrypt, 2},
    {Tincture, :export, 1},
    {Tincture, :export, 2},
    {Tincture, :fill, 1},
    {Tincture, :fill_even_odd, 1},
    {Tincture, :image_jpeg, 6},
    {Tincture, :image_png, 6},
    {Tincture, :line, 5},
    {Tincture, :line, 6},
    {Tincture, :line_to, 3},
    {Tincture, :linear_gradient, 6},
    {Tincture, :linear_gradient, 7},
    {Tincture, :link, 6},
    {Tincture, :link, 7},
    {Tincture, :move_to, 3},
    {Tincture, :new, 0},
    {Tincture, :page_size, 2},
    {Tincture, :pdf_a_violations, 1},
    {Tincture, :pdf_ua_violations, 1},
    {Tincture, :push_button, 6},
    {Tincture, :push_button, 7},
    {Tincture, :radial_gradient, 6},
    {Tincture, :radial_gradient, 7},
    {Tincture, :radio_group, 3},
    {Tincture, :radio_group, 4},
    {Tincture, :rectangle, 5},
    {Tincture, :rectangle, 6},
    {Tincture, :register_otf_font, 3},
    {Tincture, :register_otf_font, 4},
    {Tincture, :register_ttf_font, 3},
    {Tincture, :register_ttf_font, 4},
    {Tincture, :restore_state, 1},
    {Tincture, :save, 2},
    {Tincture, :save, 3},
    {Tincture, :save_state, 1},
    {Tincture, :set_alpha, 1},
    {Tincture, :set_alpha, 2},
    {Tincture, :set_dash, 3},
    {Tincture, :set_fill_color, 2},
    {Tincture, :set_font, 3},
    {Tincture, :set_language, 2},
    {Tincture, :set_line_cap, 2},
    {Tincture, :set_line_join, 2},
    {Tincture, :set_line_width, 2},
    {Tincture, :set_metadata, 2},
    {Tincture, :set_miter_limit, 2},
    {Tincture, :set_page, 2},
    {Tincture, :set_pdf_a, 2},
    {Tincture, :set_stroke_color, 2},
    {Tincture, :sign, 3},
    {Tincture, :signature_field, 6},
    {Tincture, :signature_field, 7},
    {Tincture, :stroke, 1},
    {Tincture, :tag, 3},
    {Tincture, :tag, 4},
    {Tincture, :tagged?, 1},
    {Tincture, :text_at, 4},
    {Tincture, :text_at_rotated, 5},
    {Tincture, :text_at_rotated_with_fallback, 5},
    {Tincture, :text_at_rotated_with_fallback, 6},
    {Tincture, :text_at_rotated_with_fallback, 7},
    {Tincture, :text_at_with_fallback, 4},
    {Tincture, :text_at_with_fallback, 5},
    {Tincture, :text_at_with_fallback, 6},
    {Tincture, :text_field, 6},
    {Tincture, :text_field, 7},
    {Tincture, :text_link, 5},
    {Tincture, :text_link, 6},
    {Tincture, :text_paragraph, 5},
    {Tincture, :text_paragraph, 6},
    {Tincture.Font.Binary, :bytes, 3},
    {Tincture.Font.Binary, :s16, 2},
    {Tincture.Font.Binary, :s16_list, 1},
    {Tincture.Font.Binary, :slice, 3},
    {Tincture.Font.Binary, :u16, 2},
    {Tincture.Font.Binary, :u16_list, 1},
    {Tincture.Font.Binary, :u32, 2},
    {Tincture.Font.Binary, :u32_list, 1},
    {Tincture.Font.CFF, :decode_index_offsets, 2},
    {Tincture.Font.CFF, :fixed_16_16_to_number, 1},
    {Tincture.Font.CFF, :nondecreasing?, 1},
    {Tincture.Font.CFF, :normalize_name_value, 1},
    {Tincture.Font.CFF, :parse_dict_number, 1},
    {Tincture.Font.CFF, :parse_index, 1},
    {Tincture.Font.CFF, :parse_index_objects, 3},
    {Tincture.Font.CFF, :parse_real_number, 1},
    {Tincture.Font.Context, :from_pdf, 1},
    {Tincture.Font.Context, :kerning_codepoint, 1},
    {Tincture.Font.Context, :measurable?, 2},
    {Tincture.Font.Context, :measure, 4},
    {Tincture.Font.Context, :new, 0},
    {Tincture.Font.Context, :pair_kerning_units, 3},
    {Tincture.Font.Context, :text_width, 4},
    {Tincture.Font.Context, :text_width, 5},
    {Tincture.Font.OpenType.GPOS, :begin_guardrail_scope, 0},
    {Tincture.Font.OpenType.GPOS, :end_guardrail_scope, 1},
    {Tincture.Font.OpenType.GPOS, :guardrail_scope_key, 0},
    {Tincture.Font.OpenType.GPOS, :guardrail_skips, 0},
    {Tincture.Font.TTF, :parse_basic_tables, 1},
    {Tincture.Font.UnicodeRanges, :all_zero?, 1},
    {Tincture.Font.UnicodeRanges, :bit_for_codepoint, 1},
    {Tincture.Font.UnicodeRanges, :supports_codepoint?, 2},
    {Tincture.Layout.Box, :flow_across_boxes, 3},
    {Tincture.Layout.Box, :flow_across_boxes, 4},
    {Tincture.Layout.Box, :flow_text, 6},
    {Tincture.Layout.Box, :flow_text, 7},
    {Tincture.Layout.Table, :render, 5},
    {Tincture.Layout.Table, :render, 6},
    {Tincture.Layout.Template, :new, 0},
    {Tincture.Layout.Template, :new, 1},
    {Tincture.Layout.Template, :parse_xml, 1},
    {Tincture.Layout.Template, :render, 3},
    {Tincture.Layout.Template, :render, 4},
    {Tincture.Layout.Template, :render_document, 3},
    {Tincture.Layout.Template, :render_document, 4},
    {Tincture.Layout.Template, :render_xml_document, 2},
    {Tincture.Layout.Template, :render_xml_document, 3},
    {Tincture.Layout.Template, :with_footer, 2},
    {Tincture.Layout.Template, :with_footer, 3},
    {Tincture.Layout.Template, :with_header, 2},
    {Tincture.Layout.Template, :with_header, 3},
    {Tincture.PDF, :add_link, 3},
    {Tincture.PDF, :add_radio_group, 4},
    {Tincture.PDF, :begin_artifact, 1},
    {Tincture.PDF, :begin_structure, 2},
    {Tincture.PDF, :begin_structure, 3},
    {Tincture.PDF, :end_artifact, 1},
    {Tincture.PDF, :end_structure, 1},
    {Tincture.PDF, :set_language, 2},
    {Tincture.PDF, :set_pdf_a, 2},
    {Tincture.PDF, :set_signature, 3},
    {Tincture.PDF, :tagged?, 1},
    {Tincture.PDF.Accessibility, :describe, 1},
    {Tincture.PDF.Accessibility, :violations, 1},
    {Tincture.PDF.Archival, :describe, 1},
    {Tincture.PDF.Archival, :violations, 1},
    {Tincture.PDF.CMS, :sign_detached, 6},
    {Tincture.PDF.Encrypt, :encrypt, 2},
    {Tincture.PDF.Encrypt, :encrypt_dictionary, 1},
    {Tincture.PDF.Encrypt, :encrypt_object, 2},
    {Tincture.PDF.Encrypt, :id, 1},
    {Tincture.PDF.Encrypt, :new, 0},
    {Tincture.PDF.Encrypt, :new, 1},
    {Tincture.PDF.Encrypt, :permission_flags, 1},
    {Tincture.PDF.ICC, :components, 0},
    {Tincture.PDF.ICC, :output_condition_identifier, 0},
    {Tincture.PDF.ICC, :srgb, 0},
    {Tincture.PDF.Object, :encode_text, 2},
    {Tincture.PDF.Object, :escape_byte, 1},
    {Tincture.PDF.Object, :format_text, 1},
    {Tincture.PDF.Object, :format_text, 2},
    {Tincture.PDF.Object, :num, 1},
    {Tincture.PDF.Object, :sanitize_name, 1},
    {Tincture.PDF.Object, :unicode_text?, 1},
    {Tincture.PDF.Sign, :apply_signature, 2},
    {Tincture.PDF.Sign, :default_reserved_bytes, 0},
    {Tincture.PDF.Sign, :placeholder_dictionary, 1},
    {Tincture.PDF.Structure, :container?, 1},
    {Tincture.PDF.Structure, :content?, 1},
    {Tincture.PDF.Structure, :empty?, 1},
    {Tincture.PDF.Structure, :flatten, 1},
    {Tincture.PDF.Structure, :tag_name, 1},
    {Tincture.PDF.Structure, :tags, 0},
    {Tincture.Telemetry, :enabled?, 0},
    {Tincture.Telemetry, :execute, 3},
    {Tincture.Telemetry, :span, 3},
    {Tincture.Test.MeasurableFont, :advance_units, 1},
    {Tincture.Test.MeasurableFont, :binary, 0},
    {Tincture.Test.MeasurableFont, :expected_width, 2},
    {Tincture.Test.MeasurableFont, :units_per_em, 0},
    {Tincture.Test.MeasurableFont, :write!, 0},
    {Tincture.Test.PKI, :generate, 0},
    {Tincture.Test.PKI, :generate, 1},
    {Tincture.Test.PKI, :verify_detached, 3},
    {Tincture.Typography, :layout_paragraph, 2},
    {Tincture.Typography, :layout_paragraph, 3},
    {Tincture.Typography, :layout_paragraph_with_spill, 3},
    {Tincture.Typography, :layout_paragraph_with_spill, 4},
    {Tincture.Typography.Hyphen, :hyphenate, 1},
    {Tincture.Typography.Hyphen, :hyphenate, 2},
    {Tincture.Typography.Hyphen, :hyphenate, 3},
    {Tincture.Typography.RichText, :from_plain, 1},
    {Tincture.Typography.RichText, :from_plain, 2},
    {Tincture.Typography.RichText, :from_runs, 1},
    {Tincture.Typography.RichText, :from_runs, 2},
    {Tincture.Typography.RichText, :from_tokens, 1},
    {Tincture.Typography.RichText, :remeasure, 2},
    {Tincture.Typography.RichText, :unmeasured_fonts, 1}
  ]

  # Exported but `@doc false` since fed8a34 ("hide the internals that did not need
  # them"). That commit made them internal to the library while explicitly keeping
  # them callable — "They remain public and callable; they leave the generated docs."
  # So a 0.3.2 user can still be calling them, and they stay protected here.
  #
  # These are the ones to drop at the next major version. Removing one is a deliberate
  # act: delete the entry here, in the commit that removes the function.
  @internal_published [
    {Tincture.Font.CFF, :cff_sid_to_string, 2},
    {Tincture.Font.CFF, :extract_cff_escaped_operator_operand, 2},
    {Tincture.Font.CFF, :extract_cff_operator_operand, 2},
    {Tincture.Font.CFF, :extract_cff_operator_operands, 2},
    {Tincture.Font.CFF, :fetch_cff_metadata, 2},
    {Tincture.Font.CFF, :fetch_cff_top_dict, 2},
    {Tincture.Font.OpenType.Common, :filter_open_type_lookup_entries_by_features, 4},
    {Tincture.Font.OpenType.Common, :invert_cmap_by_code, 1},
    {Tincture.Font.OpenType.Common, :parse_layout_table_metadata, 3},
    {Tincture.Font.OpenType.Common, :parse_open_type_coverage_table, 2},
    {Tincture.Font.OpenType.Common, :parse_open_type_layout_table, 1},
    {Tincture.Font.OpenType.Common, :parse_open_type_lookup_entries, 2},
    {Tincture.Font.OpenType.Common, :valid_unicode_codepoint?, 1},
    {Tincture.Font.OpenType.GPOS, :parse_gpos_pair_kerns, 3},
    {Tincture.Font.OpenType.GSUB, :parse_gsub_ligatures, 3},
    {Tincture.Font.OpenType.GSUB, :parse_gsub_ligatures_all_scripts, 3},
    {Tincture.Font.OpenType.GSUB, :parse_gsub_substitutions_all_scripts, 3},
    {Tincture.Font.TTF.Cmap, :parse_cmap_by_code, 2},
    {Tincture.Font.TTF.Cmap, :parse_cmap_variation_metadata, 2},
    {Tincture.Font.TTF.Glyf, :parse_glyph_metrics, 4},
    {Tincture.Font.TTF.Name, :parse_name_metadata, 2},
    {Tincture.PDF, :add_bookmark, 3},
    {Tincture.PDF, :add_form_field, 5},
    {Tincture.PDF, :add_link, 4},
    {Tincture.PDF, :add_page, 1},
    {Tincture.PDF, :append_current_op, 2},
    {Tincture.PDF, :page_annotations, 2},
    {Tincture.PDF, :page_numbers, 1},
    {Tincture.PDF, :page_operations, 2},
    {Tincture.PDF, :register_image, 2},
    {Tincture.PDF, :register_otf_font, 3},
    {Tincture.PDF, :register_otf_font, 4},
    {Tincture.PDF, :register_ttf_font, 3},
    {Tincture.PDF, :register_ttf_font, 4},
    {Tincture.PDF, :set_metadata, 2},
    {Tincture.PDF, :set_page, 2},
    {Tincture.PDF.FontEmbed, :build_embedded_font_objects, 3},
    {Tincture.PDF.FontEmbed, :font_names_from_operations, 1},
    {Tincture.PDF.Serialize, :export, 1}
  ]

  defp current_api do
    for module <- Application.spec(:tincture, :modules) || [],
        Code.ensure_loaded?(module),
        {name, arity} <- module.__info__(:functions),
        into: MapSet.new(),
        do: {module, name, arity}
  end

  test "every function published in v0.3.2 still exists with the same name and arity" do
    current = current_api()

    missing =
      for {kind, entries} <- [documented: @public_api, internal: @internal_published],
          entry <- entries,
          not MapSet.member?(current, entry),
          do: {kind, entry}

    assert missing == [],
           """
           #{length(missing)} function(s) published in v0.3.2 are gone or changed arity.

           This breaks semver for a released package. If it is intentional, remove the
           entries below from @public_api / @internal_published in this same commit.

           #{Enum.map_join(missing, "\n", fn {kind, {module, name, arity}} -> "  [#{kind}] #{inspect(module)}.#{name}/#{arity}" end)}
           """
  end
end
